year: 2019
sample_size: 300000
random_seed: 69




tree_max_depth: 3
tree_min_samples_leaf: 200


adaptive_cv_threshold: 0.5


n_estimators: 1500
forest_min_samples_leaf: 150
model_n_estimators: 500

output_dir: "results/causal"

gcs:
  bucket: "enem-lake-joao-luca"