year: 2019
sample_size: 500000
random_seed: 69


standardize_treatment: true


tree_max_depth: 3
tree_min_samples_leaf: 200


n_estimators: 1500
forest_min_samples_leaf: 100


model_n_estimators: 500

treatments:
  - RENDA
  - SCORE_CULT_PAIS

output_dir: "results/causal"

gcs:
  bucket: "enem-lake-joao-luca"