year: 2019
sample_size: 100000
random_seed: 69

# Padroniza treatment e outcome para desvio-padrão
# ATE interpretado como: "1 std de treatment -> X std de outcome"
standardize_treatment: true



tree_max_depth: 3
tree_min_samples_leaf: 500   



n_estimators: 300
model_n_estimators: 200
forest_min_samples_leaf: 20

treatments:
  - RENDA
  - SCORE_CULT_PAIS

output_dir: "results/causal"

gcs:
  bucket: "enem-lake-joao-luca"